export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

// Журнал поверок
export const CHECKS_CARD_LOADED = 'CHECKS_VIEW_PAGE_LOADED';
export const CHECKS_CARD_UNLOADED = 'CHECKS_CARD_UNLOADED';
export const CHECKS_CARD_CHANGED = 'CHECKS_CARD_CHANGED';
export const CHECKS_CARD_INITFORM = 'CHECKS_CARD_INITFORM';
// Подразделение
export const DEPARTMENT_CARD_LOADED = 'DEPARTMENT_VIEW_PAGE_LOADED';
export const DEPARTMENT_CARD_UNLOADED = 'DEPARTMENT_CARD_UNLOADED';
export const DEPARTMENT_CARD_CHANGED = 'DEPARTMENT_CARD_CHANGED';
export const DEPARTMENT_CARD_INITFORM = 'DEPARTMENT_CARD_INITFORM';
// Вид документа
export const DOCUMENT_KIND_CARD_LOADED = 'DOCUMENT_KIND_VIEW_PAGE_LOADED';
export const DOCUMENT_KIND_CARD_UNLOADED = 'DOCUMENT_KIND_CARD_UNLOADED';
export const DOCUMENT_KIND_CARD_CHANGED = 'DOCUMENT_KIND_CARD_CHANGED';
export const DOCUMENT_KIND_CARD_INITFORM = 'DOCUMENT_KIND_CARD_INITFORM';
// Оборудование
export const EQUIPMENT_CARD_LOADED = 'EQUIPMENT_VIEW_PAGE_LOADED';
export const EQUIPMENT_CARD_UNLOADED = 'EQUIPMENT_CARD_UNLOADED';
export const EQUIPMENT_CARD_CHANGED = 'EQUIPMENT_CARD_CHANGED';
export const EQUIPMENT_CARD_INITFORM = 'EQUIPMENT_CARD_INITFORM';
// Статус оборудование
export const EQUIPMENT_TAGS_CARD_LOADED = 'EQUIPMENT_TAGS_VIEW_PAGE_LOADED';
export const EQUIPMENT_TAGS_CARD_UNLOADED = 'EQUIPMENT_TAGS_CARD_UNLOADED';
export const EQUIPMENT_TAGS_CARD_CHANGED = 'EQUIPMENT_TAGS_CARD_CHANGED';
export const EQUIPMENT_TAGS_CARD_INITFORM = 'EQUIPMENT_TAGS_CARD_INITFORM';
// Типы оборудования
export const EQUIPMENT_TYPES_CARD_LOADED = 'EQUIPMENT_TYPES_VIEW_PAGE_LOADED';
export const EQUIPMENT_TYPES_CARD_UNLOADED = 'EQUIPMENT_TYPES_CARD_UNLOADED';
export const EQUIPMENT_TYPES_CARD_CHANGED = 'EQUIPMENT_TYPES_CARD_CHANGED';
export const EQUIPMENT_TYPES_CARD_INITFORM = 'EQUIPMENT_TYPES_CARD_INITFORM';
// Инструкции
export const INSTRUCTION_CARD_LOADED = 'INSTRUCTION_VIEW_PAGE_LOADED';
export const INSTRUCTION_CARD_UNLOADED = 'INSTRUCTION_CARD_UNLOADED';
export const INSTRUCTION_CARD_CHANGED = 'INSTRUCTION_CARD_CHANGED';
export const INSTRUCTION_CARD_INITFORM = 'INSTRUCTION_CARD_INITFORM';
// Местоположение
export const LOCATION_CARD_LOADED = 'LOCATION_CARD_LOADED';
export const LOCATION_CARD_UNLOADED = 'LOCATION_CARD_UNLOADED';
export const LOCATION_CARD_CHANGED = 'LOCATION_CARD_CHANGED';
export const LOCATION_CARD_INITFORM = 'LOCATION_CARD_INITFORM';
// Производитель
export const MANUFACTURER_CARD_LOADED = 'MANUFACTURER_CARD_LOADED';
export const MANUFACTURER_CARD_UNLOADED = 'MANUFACTURER_CARD_UNLOADED';
export const MANUFACTURER_CARD_CHANGED = 'MANUFACTURER_CARD_CHANGED';
export const MANUFACTURER_CARD_INITFORM = 'MANUFACTURER_CARD_INITFORM';
// Роли
export const ROLE_CARD_LOADED = 'ROLE_CARD_LOADED';
export const ROLE_CARD_UNLOADED = 'ROLE_CARD_UNLOADED';
export const ROLE_CARD_CHANGED = 'ROLE_CARD_CHANGED';
export const ROLE_CARD_INITFORM = 'ROLE_CARD_INITFORM';
// Сотрудники
export const USER_CARD_LOADED = 'USER_VIEW_PAGE_LOADED';
export const USER_CARD_UNLOADED = 'USER_CARD_UNLOADED';
export const USER_CARD_CHANGED = 'USER_CARD_CHANGED';
export const USER_CARD_INITFORM = 'USER_CARD_INITFORM';
// Поверки
export const VERIFICATIONS_CARD_LOADED = 'VERIFICATIONS_VIEW_PAGE_LOADED';
export const VERIFICATIONS_CARD_UNLOADED = 'VERIFICATIONS_CARD_UNLOADED';
export const VERIFICATIONS_CARD_CHANGED = 'VERIFICATIONS_CARD_CHANGED';
export const VERIFICATIONS_CARD_INITFORM = 'VERIFICATIONS_CARD_INITFORM';

