export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const CHANGE_TAB = 'CHANGE_TAB';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const EQUIPMENT_VIEW_PAGE_LOADED = 'EQUIPMENT_VIEW_PAGE_LOADED';
export const LOCATION_CARD_LOADED = 'LOCATION_CARD_LOADED';
export const LOCATION_CARD_UNLOADED = 'LOCATION_CARD_UNLOADED';
export const LOCATION_CARD_CHANGED = 'LOCATION_CARD_CHANGED';
export const LOCATION_CARD_INITFORM = 'LOCATION_CARD_INITFORM';